# render.yaml
services:
  # Service 1: The Web Control Panel
  - type: web
    name: bot-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web_app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: FLASK_SECRET_KEY
        generateValue: true

  # Service 2: The Discord Bot Worker
  - type: worker
    name: bot-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_worker.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4