# render.yaml
services:
  # 服務一：網頁控制面板 (Web UI)
  - type: web
    name: bot-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web_app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: FLASK_SECRET_KEY
        generateValue: true
    disk:
      name: bot-data
      mountPath: /var/data/render
      sizeGB: 1

  # 服務二：Discord Bot (背景程式)
  - type: worker
    name: bot-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_worker.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
    disk:
      name: bot-data
      mountPath: /var/data/render